#!/bin/bash

if [ "$#" -ne 2 ]
then
    echo
    echo "Returns statistics regarding status, checking a list of status against a generated report file."
    echo
    echo "Usage: \"get-status-stats <input_file> <status_list>\""
    echo
    exit -1
fi

INPUT=$1
STATUSES=$2

TOTAL=0
DATA=`cat $STATUSES`
for FIELD in $DATA ;
do
    COUNT=$(grep -c ",$FIELD" $INPUT)
    echo $FIELD,$COUNT
    TOTAL=$(($TOTAL+$COUNT))
done

echo ,
echo TOTAL,$TOTAL

exit 0
