#!/bin/bash

if [ "$#" -ne 2 ];
then
    echo ""
    echo "Returns information of reviews matching the pattern. Results are return under a json format"
    echo ""
    echo "Usage: \"get-gerrit-info <project> <pattern>\""
    echo ""
    echo "Note: <pattern> is treated as a regular expression and is case insensitive."
    echo ""
    exit -1
fi

PROJECT=$1
PATTERN=$2

ssh review.tizen.org gerrit query --format json "project:$PROJECT" | grep -iE "$PATTERN"

exit 0
