#!/bin/bash

if [ "$#" -ne 1 ];
then
    echo
    echo "Returns the list of commits which are ready to be merged. Only returns the commits that are older than the number of days given as parameter."
    echo
    echo "Returns the commits that:"
    echo "* have at least one code-review +2"
    echo "* have at least one verified +1"
    echo "* don't have a code review -2"
    echo "* don't have a verified -1"
    echo "* are more than 'N' days old"
    echo
    echo "The return format is json."
    echo
    echo "Usage: \"get-ready-to-merge <number_of_days>\""
    echo
    exit -1
fi

AGE=$1

ssh review.tizen.org gerrit query --format json "is:open age:${AGE}d label:Code-Review+2 label:Verified+1 NOT label:Verified-1 NOT label:Code-Review-2"