#!/bin/bash

if [ "$#" -ne 1 ];
then
    echo
    echo "Returns the list of commits that need to be verified. Only returns the commits that are older than the number of days given as parameter."
    echo
    echo "Returns the commits that:"
    echo "* don't have either a verified +1 or -1"
    echo "* have a code review +2 but no code review -2"
    echo "* are more than 'N' days old"
    echo
    echo "The return format is json."
    echo
    echo "Usage: \"get-to-verify <number_of_days>\""
    echo
    exit -1
fi

AGE=$1

ssh review.tizen.org gerrit query --format json "status:open age:${AGE}d label:Code-Review+2 NOT label:Verified+1 NOT label:Verified-1 NOT label:Code-Review-2"