#!/bin/bash

# Copyright (c) 2014 Kévin THIERRY <kevin.thierry@open.eurogiciel.org>

# See the file LICENSE for copying permission.

if [ "$#" -ne 4 ]
then
    echo ""
    echo "Return the commit with the given changeid"
    echo ""
    echo "Usage: \"get-commit <local_repo> <project> <branch> <changeid>\""
    echo ""
    exit -1
fi

REPO=$1
PROJECT=$2
BRANCH=$3
CHANGEID=$4

cd $REPO/$PROJECT &> /dev/null
git checkout $BRANCH &> /dev/null

COMMIT=$(git log --grep="$CHANGEID" | head -n 1 | cut -f 2 -d ' ')

cd - &> /dev/null

echo $COMMIT

exit 0
